# Generated by Django 3.1.5 on 2021-01-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20210122_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
